In [1]:
import numpy as np

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
list_ = [ '1' ,'2' ,'3' ,'4', '5' ]
type(list_)

list

In [3]:
array_list = np.array(object = list_)
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
for i in list_:
    print(i)

1
2
3
4
5


In [5]:
for i in array_list:
    print(i)

1
2
3
4
5


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [6]:
list_ = [ '1' ,'2' ,'3' ,'4', '5' ]
type(list_)

list

In [7]:
array_list = np.array(object = list_, dtype = int)
type(array_list)

numpy.ndarray

In [8]:
for i in list_:
    print(i)

1
2
3
4
5


In [9]:
for i in array_list:
    print(i)

1
2
3
4
5


Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [10]:
num_list = [ [ 1 , 2 , 3 ] , [ 4, 5 , 6 ] ]

num_array = np.array(object = num_list)

In [11]:
num_array.shape
# (2,3) mean 2D and 3 element in each

(2, 3)

In [12]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
import numpy as np
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr.shape

(3, 3)

In [15]:
arr.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
arr1 = np.identity(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
arr1.shape

(5, 5)

In [18]:
arr1.size

25

In [19]:
a = np.array([1,2,4])
b = np.array([1,2,5])

In [20]:
np.multiply(a,b)

array([ 1,  4, 20])

In [21]:
np.dot(a,b)

25

In [22]:
a*b

array([ 1,  4, 20])

In [23]:
 np.unique(a)

array([1, 2, 4])

In [24]:
np.distinct(a)

AttributeError: module 'numpy' has no attribute 'distinct'

In [ ]:
np.concatenate((a, b))

In [ ]:
c = np.array([1,2,3])
d = np.array([6,7,8])


In [ ]:
np.power(c,2)

In [ ]:
e = np.array(['q' , 'w'])
np.flip(e)

In [ ]:
f = np.array([2,4,21,67,3])
np.argsort(f)

In [ ]:
np.ndarray.copy(f)

In [ ]:
# np.byteswap(f)