In [1]:
import numpy as np

In [2]:
#Sort, Search & Counting Functions.
arr = np.array([1,2,3,4,5,7,3,2,4,6,6,8,7,2334,4,6,534,2])

In [3]:
np.sort(arr)

array([   1,    2,    2,    2,    3,    3,    4,    4,    4,    5,    6,
          6,    6,    7,    7,    8,  534, 2334])

In [4]:
arr.max()

2334

In [5]:
np.searchsorted(arr , 8)

16

In [6]:
arr1 = np.array([0,3,0,42,42,5,0])

In [7]:
np.count_nonzero(arr1)

4

In [8]:
# Return elements chosen from `x` or `y` depending on `condition`.
np.where(arr >5)

(array([ 5,  9, 10, 11, 12, 13, 15, 16], dtype=int64),)

In [9]:
# extract:Return the elements of an array that satisfy some condition.
np.extract(arr >10 , arr)

array([2334,  534])

In [10]:
#Numpy - Byte Swapping.
arr

array([   1,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [11]:
arr.byteswap()

array([ 16777216,  33554432,  50331648,  67108864,  83886080, 117440512,
        50331648,  33554432,  67108864, 100663296, 100663296, 134217728,
       117440512, 503906304,  67108864, 100663296, 369229824,  33554432])

In [12]:
# copies and views

In [13]:
arr

array([   1,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [14]:
a = np.copy(arr)# call them deep copy
a

array([   1,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [15]:
# view: it does not create newdata like copy()
b = arr.view() #it also create copy. if change in a doesnot reflect in a
b

array([   1,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [16]:
arr

array([   1,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [17]:
b[0] = 73
b

array([  73,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [18]:
arr

array([  73,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [19]:
a[1] = 23

In [20]:
b

array([  73,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [21]:
arr

array([  73,    2,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [22]:
a

array([   1,   23,    3,    4,    5,    7,    3,    2,    4,    6,    6,
          8,    7, 2334,    4,    6,  534,    2])

In [23]:
import numpy.matlib as nm
# this used to create matrix

In [24]:
nm.zeros(6)

matrix([[0., 0., 0., 0., 0., 0.]])

In [25]:
nm.ones(4)

matrix([[1., 1., 1., 1.]])

In [26]:
nm.random.randint(1,4 , (3,4))

array([[2, 2, 2, 2],
       [2, 1, 3, 2],
       [2, 2, 3, 1]])

In [27]:
nm.eye(6)

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [31]:
# linear algebra
arr1 = np.random.randint([[2,3] , [4,5]])
arr2 = np.random.randint([[5,3] , [2,5]])

In [32]:
arr1

array([[0, 2],
       [1, 1]])

In [33]:
arr2

array([[3, 1],
       [0, 2]])

In [34]:
np.dot(arr1,arr2)

array([[0, 4],
       [3, 3]])

In [35]:
arr1@arr2

array([[0, 4],
       [3, 3]])