In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10, (3,4))
arr

array([[4, 3, 3, 9],
       [3, 5, 6, 6],
       [9, 4, 1, 6]])

In [3]:
arr.reshape(6,2)

array([[4, 3],
       [3, 9],
       [3, 5],
       [6, 6],
       [9, 4],
       [1, 6]])

In [4]:
arr.reshape(6,-13222353)

array([[4, 3],
       [3, 9],
       [3, 5],
       [6, 6],
       [9, 4],
       [1, 6]])

In [26]:
arr.T

array([[4, 3, 9],
       [3, 5, 4],
       [3, 6, 1],
       [9, 6, 6]])

In [27]:
arr.flatten()

array([4, 3, 3, 9, 3, 5, 6, 6, 9, 4, 1, 6])

In [28]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [29]:
arr1.T

array([1, 2, 3, 4])

In [35]:
#  transpose the one dimension array
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [39]:
sque = np.random.randint(1,4, (3,4))
sque

array([[3, 1, 1, 3],
       [1, 3, 3, 3],
       [2, 3, 3, 2]])

In [41]:
np.squeeze(sque)
# note

array([[3, 1, 1, 3],
       [1, 3, 3, 3],
       [2, 3, 3, 2]])

In [43]:
sque1 = np.array([[1] , [2] , [3]])
sque1

array([[1],
       [2],
       [3]])

In [44]:
np.squeeze(sque1)# it works on single data

array([1, 2, 3])

In [47]:
# repeat the array
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [48]:
# reshuffle the array element by its position
np.roll(arr1 , 2)

array([3, 4, 1, 2])

In [49]:
arr1

array([1, 2, 3, 4])

In [54]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
np.diagonal(arr)

array([4, 5, 1])

In [53]:
arr

array([[4, 3, 3, 9],
       [3, 5, 6, 6],
       [9, 4, 1, 6]])

In [56]:
# Binary operators
arr2 = np.random.randint(1,10 , (3,4))
arr3 = np.random.randint(1,10 , (3,4))

In [57]:
arr2

array([[6, 4, 4, 1],
       [4, 4, 9, 3],
       [1, 5, 8, 4]])

In [58]:
arr3

array([[5, 3, 2, 9],
       [7, 2, 2, 4],
       [5, 8, 8, 3]])

In [59]:
arr2/arr3

array([[1.2       , 1.33333333, 2.        , 0.11111111],
       [0.57142857, 2.        , 4.5       , 0.75      ],
       [0.2       , 0.625     , 1.        , 1.33333333]])

In [60]:
arr2**arr3

array([[    7776,       64,       16,        1],
       [   16384,       16,       81,       81],
       [       1,   390625, 16777216,       64]], dtype=int32)

In [61]:
arr2+arr3

array([[11,  7,  6, 10],
       [11,  6, 11,  7],
       [ 6, 13, 16,  7]])

In [62]:
arr2%arr3

array([[1, 1, 0, 1],
       [4, 0, 1, 3],
       [1, 5, 0, 1]], dtype=int32)

In [63]:
~arr2

array([[ -7,  -5,  -5,  -2],
       [ -5,  -5, -10,  -4],
       [ -2,  -6,  -9,  -5]], dtype=int32)

In [70]:
arr2>arr3

array([[ True,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [73]:
# string function
arr4 = np.array(['hello' , 'apple' , 'google'])

In [76]:
np.char.capitalize(arr4)

array(['Hello', 'Apple', 'Google'], dtype='<U6')

In [79]:
np.char.count(arr4, 'o')

array([1, 0, 2])

In [80]:
np.char.upper(arr4)

array(['HELLO', 'APPLE', 'GOOGLE'], dtype='<U6')

In [82]:
np.char.find(arr4,'e')

array([1, 4, 5])

In [84]:
arr2

array([[6, 4, 4, 1],
       [4, 4, 9, 3],
       [1, 5, 8, 4]])

In [83]:
# mathematical operation
np.sin(arr2)

array([[-0.2794155 , -0.7568025 , -0.7568025 ,  0.84147098],
       [-0.7568025 , -0.7568025 ,  0.41211849,  0.14112001],
       [ 0.84147098, -0.95892427,  0.98935825, -0.7568025 ]])

In [85]:
np.log10(arr2)

array([[0.77815125, 0.60205999, 0.60205999, 0.        ],
       [0.60205999, 0.60205999, 0.95424251, 0.47712125],
       [0.        , 0.69897   , 0.90308999, 0.60205999]])

In [86]:
np.tan(arr2)

array([[-0.29100619,  1.15782128,  1.15782128,  1.55740772],
       [ 1.15782128,  1.15782128, -0.45231566, -0.14254654],
       [ 1.55740772, -3.38051501, -6.79971146,  1.15782128]])

In [88]:
np.power(arr2,2)

array([[36, 16, 16,  1],
       [16, 16, 81,  9],
       [ 1, 25, 64, 16]], dtype=int32)

In [90]:
np.sqrt(arr2)

array([[2.44948974, 2.        , 2.        , 1.        ],
       [2.        , 2.        , 3.        , 1.73205081],
       [1.        , 2.23606798, 2.82842712, 2.        ]])

In [91]:
np.mean(arr2)

4.416666666666667

In [92]:
np.std(arr2)

2.289771944005681