In [1]:
import numpy as np

In [2]:
l = [1,2,4,2,5]


In [3]:
ar = np.array(l)
ar

array([1, 2, 4, 2, 5])

In [4]:
# nd mean n dimensional data
type(ar)

numpy.ndarray

In [5]:
# Create an array.
np.array( [[1,2,3] , [4,5,6]] )

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Convert the input to an array.
np.asarray(l)

array([1, 2, 4, 2, 5])

In [7]:
# Convert the input to an ndarray, but pass ndarray subclasses through.
np.asanyarray(l)

array([1, 2, 4, 2, 5])

In [8]:
# matrix is subset of array.because matrix is 2D and array is nD
b = np.matrix(l)
b

matrix([[1, 2, 4, 2, 5]])

In [9]:
type(b)

numpy.matrix

In [10]:
# np.asanyarray(b) : This function is not convert into array . because matrix is array subset
# np.asanyarray(): it convert input(except array) into array
np.asanyarray(b)

matrix([[1, 2, 4, 2, 5]])

In [11]:
a = np.array(l)
a

array([1, 2, 4, 2, 5])

In [12]:
c = a # c having  refrence to a 
c

array([1, 2, 4, 2, 5])

In [13]:
c[0] = 1294 #note
a

array([1294,    2,    4,    2,    5])

In [14]:
d = np.copy(a) # d copying the value of a

In [15]:
d

array([1294,    2,    4,    2,    5])

In [16]:
a[1] = 122
a

array([1294,  122,    4,    2,    5])

In [17]:
d

array([1294,    2,    4,    2,    5])

In [18]:
# Construct an array by executing a function over each coordinate.
np.fromfunction(lambda i,j : i==j , (3,3)) #matric->> 3x3

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [20]:
iterable = (i*i for i in range(5))

np.from

In [21]:
# fromiter(iter, dtype, count=-1, *, like=None)
# Create a new 1-dimensional array from an iterable object.

np.fromiter(iterable ,float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
# create array from string
# sep mean sperate
# A new 1-D array initialized from text data in a string.
np.fromstring('3,2,4,7,8' , sep =',')

array([3., 2., 4., 7., 8.])

In [23]:
# dimension of  numpy
l = [1,2,3,4]
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [24]:
ar.ndim

1

In [25]:
ar1 = np.array([[1,2,3,3,4] , [5,6,7,4,1]])
ar1

array([[1, 2, 3, 3, 4],
       [5, 6, 7, 4, 1]])

In [26]:
ar1.ndim

2

In [27]:
# elements in array
ar.size

4

In [28]:
ar1.size

10

In [29]:
# shape of array
# (4,) mean 4row and zero column
ar.shape

(4,)

In [30]:
# 2 row and 5 column
ar1.shape

(2, 5)

In [31]:
# datatype of array
ar1.dtype

dtype('int32')

In [32]:
ar.dtype

dtype('int32')

In [33]:
ar22 = np.array([(1,2,3.4,4) , (1,2,8,5)])
ar22

array([[1. , 2. , 3.4, 4. ],
       [1. , 2. , 8. , 5. ]])

In [34]:
ar22.dtype

dtype('float64')

In [35]:
# in list float range cannot interpreted. mean list takes online int range
# ex: list(range(2.3 , 6.4)) #typeerror 
# but in numpy this function avaible
ar33 = np.arange(2.3, 5.3)
ar33


array([2.3, 3.3, 4.3])

In [36]:
ar34 = np.arange(2.3 , 5.3, .3)
ar34

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. ])

In [37]:
ar34.dtype

dtype('float64')

In [38]:
# convert array to list
list(ar34)

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998]

In [39]:
# create a array between 1 to 1.1 of 20 elements
np.linspace(1,1.1 , 20)

array([1.        , 1.00526316, 1.01052632, 1.01578947, 1.02105263,
       1.02631579, 1.03157895, 1.03684211, 1.04210526, 1.04736842,
       1.05263158, 1.05789474, 1.06315789, 1.06842105, 1.07368421,
       1.07894737, 1.08421053, 1.08947368, 1.09473684, 1.1       ])

In [40]:
#  create null array of 3 rows and 4 columns 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# create 3 null arrays of 2x4
ar35 = np.zeros((3,2,4))
ar35

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [43]:
ar35.ndim

3

In [44]:
ar35.dtype

dtype('float64')

In [45]:
ar36 = np.zeros((3,2,4,6))
ar36

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [46]:
ar36.ndim

4

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
on=np.ones((2,2,4))
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
on+4

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [50]:
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# identical matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [53]:
# find the log of the array element
np.logspace(2,5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [54]:
np.logspace(2,5, 10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [55]:
# random data genration
# np.random.randn() : data genration from mean value.The default mean is 0 and
# std is 1
arr = np.random.randn(5,5)
arr

array([[-0.36549587,  1.12857826,  1.23536639, -0.69728538, -0.67279343],
       [-0.8721631 ,  0.42437832, -1.49458271,  1.28643692, -0.13329221],
       [ 0.98434947, -0.9374616 ,  0.46787574,  0.17399357,  1.32304613],
       [-0.46223702,  2.05913427, -0.90265243, -0.83668616,  1.7658782 ],
       [-1.36938091,  2.18608798,  0.04751426,  0.67117192, -1.88447069]])

In [56]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3         4
0 -0.365496  1.128578  1.235366 -0.697285 -0.672793
1 -0.872163  0.424378 -1.494583  1.286437 -0.133292
2  0.984349 -0.937462  0.467876  0.173994  1.323046
3 -0.462237  2.059134 -0.902652 -0.836686  1.765878
4 -1.369381  2.186088  0.047514  0.671172 -1.884471

In [57]:
arr1 = np.random.rand(4,3)

In [58]:
pd.DataFrame(arr1)

0         1         2
0  0.668275  0.561005  0.995165
1  0.994756  0.259915  0.952608
2  0.900380  0.536684  0.896109
3  0.167537  0.345342  0.900294

In [59]:
# np.random.randint
# start range = 1 , end range = 110 , matrix  = 30,40
pd.DataFrame(np.random.randint(1,110 , (30,40))).to_html('test.html')

In [60]:
np.random.rand(3,4)

array([[0.79627054, 0.55131031, 0.90256256, 0.43078367],
       [0.87052331, 0.14431346, 0.11474055, 0.7531443 ],
       [0.6982373 , 0.17205592, 0.84817705, 0.67582468]])

In [61]:
# reshape the array
# note reshape matrix row and column should equal to element of reshaping matrix
# ex: 3*4 = 12 and 6*2 = 12
(np.random.rand(3,4)).reshape(6,2)

array([[0.16116609, 0.62648655],
       [0.29933685, 0.82710486],
       [0.95298679, 0.8920459 ],
       [0.10760458, 0.38983892],
       [0.55965965, 0.65671194],
       [0.48888738, 0.52884826]])

In [62]:
arr= np.random.rand(2,6)
arr

array([[0.84140162, 0.78009732, 0.5943345 , 0.76858435, 0.67623056,
        0.40240278],
       [0.2992538 , 0.17907744, 0.18461305, 0.84875347, 0.71637994,
        0.47273553]])

In [70]:
arr1 = arr.reshape(6,2)
# application used in image processing
arr1

array([[0.84140162, 0.78009732],
       [0.5943345 , 0.76858435],
       [0.67623056, 0.40240278],
       [0.2992538 , 0.17907744],
       [0.18461305, 0.84875347],
       [0.71637994, 0.47273553]])

In [71]:
arr[0]

array([0.84140162, 0.78009732, 0.5943345 , 0.76858435, 0.67623056,
       0.40240278])

In [72]:
arr[0,1]

0.7800973163997393

In [73]:
# slicing
arr[0][1]

0.7800973163997393

In [90]:
arr1[2:4]

array([[0.67623056, 0.40240278],
       [0.2992538 , 0.17907744]])

In [93]:
arr1[2:4,1]

array([0.40240278, 0.17907744])

In [95]:
# In numpy, `arr1[2:5][0,1]` means that you are selecting the elements from the 2nd to the 4th index of the first dimension of the array `arr1`, and then selecting the element at index `(0,1)` of the resulting array. The first dimension of an array is indexed by 0 and the second dimension is indexed by 1. So, `arr1[2:5]` selects rows 2 through 4 (inclusive) of `arr1`, and `[0,1]` selects the element at row 0 and column 1 of that subarray. ³

# Source: Conversation with Bing, 8/6/2023(1) what is the working of arr[arr1,arr2] in numpy - Stack Overflow. https://stackoverflow.com/questions/59498207/what-is-the-working-of-arrarr1-arr2-in-numpy Accessed 8/6/2023.
# (2) What is the meaning of arr[:] in assignment in numpy?. https://stackoverflow.com/questions/35713891/what-is-the-meaning-of-arr-in-assignment-in-numpy Accessed 8/6/2023.
# (3) Basics of NumPy Arrays - GeeksforGeeks. https://www.geeksforgeeks.org/basics-of-numpy-arrays/ Accessed 8/6/2023.
# (4) NumPy Creating Arrays - W3Schools. https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp Accessed 8/6/2023.
# (5) reshaping data in numpy with (-1,1). What does it mean?. https://stackoverflow.com/questions/57962718/reshaping-data-in-numpy-with-1-1-what-does-it-mean Accessed 8/6/2023.
arr1[2:5][0,1]

0.40240277758189336

In [105]:
arr2 = np.random.randint(1,100 , (5,5))
arr2

array([[34, 58, 88, 35, 91],
       [24, 31, 65, 48, 28],
       [96,  3, 31, 95, 56],
       [98, 66, 71, 45, 75],
       [77, 59, 36, 53, 28]])

In [103]:
# condition apply on arr
# o/p: bool
arr2 > 50 

array([[False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [False,  True, False, False, False],
       [ True,  True, False, False, False]])

In [104]:
# extracted the value from # condition apply on arr
arr2[arr2>50]

array([84, 88, 72, 61, 69, 76, 66, 71, 59, 60, 81, 82, 83])

In [117]:
# extracted  the particular data from array
#  2:4 : select the row from 2 to 4
# print the value of position of 1 to 2
# note row 2nd now 0th row because we select the matrix from 2:4.But not change in columns
arr2[2:4,[1,2]]

array([[ 3, 31],
       [66, 71]])

In [118]:
arr2[3:4,[3,4]]

array([[45, 75]])

In [119]:
arr2[2:4][1,2]

71

In [116]:
# this method give the particular positon of element in array
# synatx: arr_name[array][position of element]
arr2[1:3][1,1]

3

In [120]:
# manupulate data in array
arr2[0][0] = 382

In [121]:
arr2

array([[382,  58,  88,  35,  91],
       [ 24,  31,  65,  48,  28],
       [ 96,   3,  31,  95,  56],
       [ 98,  66,  71,  45,  75],
       [ 77,  59,  36,  53,  28]])

In [158]:
arr3 = np.random.randint(1,3,(3,3))
arr4 = np.random.randint(1,3,(3,3))

In [159]:
arr3

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 2]])

In [160]:
arr4

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [161]:
# addition: index wise
arr3+arr4

array([[3, 4, 2],
       [4, 2, 2],
       [3, 3, 3]])

In [162]:
# index wise subtraction 
arr3-arr4

array([[ 1,  0,  0],
       [ 0,  0,  0],
       [-1,  1,  1]])

In [163]:
# index wise multipication
arr3*arr4

array([[2, 4, 1],
       [4, 1, 1],
       [2, 2, 2]])

In [164]:
# index wise divison
arr3/arr4

array([[2. , 1. , 1. ],
       [1. , 1. , 1. ],
       [0.5, 2. , 2. ]])

In [165]:
# matrix multipication : @ help to matrix multipication
# matrix1 = mxn , matrix2 = pxq
# conditon : m = q
arr3@arr4

array([[8, 7, 5],
       [6, 6, 4],
       [9, 6, 5]])

In [166]:
arr1/0
# inf mean infinity

C:\Users\hp\AppData\Local\Temp\ipykernel_4684\2890472672.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf]])

In [167]:
arr3+ 1200
# arr3
# try
#  arr3 = arr3+ 1200
# arr3

array([[1202, 1202, 1201],
       [1202, 1201, 1201],
       [1201, 1202, 1202]])

In [168]:
arr3**2

array([[4, 4, 1],
       [4, 1, 1],
       [1, 4, 4]], dtype=int32)

In [176]:
# Broadcasting
arr5 = np.zeros((4,4) )
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [187]:
row1 = np.array([1,2,3,4])
row1

array([1, 2, 3, 4])

In [188]:
# adding row in array row wise
row1 + arr5

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [190]:
row1.T

array([1, 2, 3, 4])

In [191]:
row1 = np.array([[1,2,3,4]])

In [193]:
row1.T

array([[1],
       [2],
       [3],
       [4]])

In [195]:
row.T + arr5

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [199]:
arr6 = np.random.randint(1,4,(3,4))
arr6

array([[1, 2, 1, 2],
       [2, 1, 2, 3],
       [3, 3, 1, 2]])

In [200]:
np.sqrt(arr6)

array([[1.        , 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 1.        , 1.41421356]])

In [201]:
np.exp(arr6)

array([[ 2.71828183,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692],
       [20.08553692, 20.08553692,  2.71828183,  7.3890561 ]])

In [203]:
np.log10(arr6)

array([[0.        , 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.        , 0.30103   , 0.47712125],
       [0.47712125, 0.47712125, 0.        , 0.30103   ]])